config/routes.rb
Depot::Application.routes.draw do

  resources :slides

  resources :categories

  get "contacts/index"

  get "contacts/update"

  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  match "/slides/pro2slider/:id" => "slides#pro2slider"
  
  get 'register' => 'users#new'
  scope '(:locale)' do
    resources :contacts
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, on: :member
      put :decrement, on: :member
      put :increase, on: :member
    end
    root to: 'store#index', as: 'store'
  end
end

app/models/slide.rb
class Slide < ActiveRecord::Base
  attr_accessible :description, :image_url, :title, :url, :slideno
  validates :title, presence: true
  validates :image_url, presence: true
  validates :url, presence: true
  validates :description, presence: true
  validates :slideno, presence: true
end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
  # GET /slides
  # GET /slides.json
  def index
    @slides = Slide.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @slides }
    end
  end

  # GET /slides/1
  # GET /slides/1.json
  def show
    @slide = Slide.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @slide }
    end
  end

  # GET /slides/new
  # GET /slides/new.json
  def new
    @slide = Slide.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @slide }
    end
  end

  # GET /slides/1/edit
  def edit
    @slide = Slide.find(params[:id])
  end

  # POST /slides
  # POST /slides.json
  def create
    @slide = Slide.new(params[:slide])

    respond_to do |format|
      if @slide.save
        format.html { redirect_to @slide, notice: 'Slide was successfully created.' }
        format.json { render json: @slide, status: :created, location: @slide }
      else
        format.html { render action: "new" }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /slides/1
  # PUT /slides/1.json
  def update
    @slide = Slide.find(params[:id])

    respond_to do |format|
      if @slide.update_attributes(params[:slide])
        format.html { redirect_to @slide, notice: 'Slide was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @slide.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /slides/1
  # DELETE /slides/1.json
  def destroy
    @slide = Slide.find(params[:id])
    @slide.destroy

    respond_to do |format|
      format.html { redirect_to slides_url }
      format.json { head :no_content }
    end
  end
  
  # 
  def pro2slider
    @product = Product.find_by_id(params[:id])
    @slide = Slide.new
    
    respond_to do |format|
      format.html 
      format.js
      format.json { head :no_content }
    end
  end
  
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/slides/_form.html.erb
<%= form_for(@slide) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  
  <div class="field">
    <%= f.label "Slide No." %><br />
    <%= f.select :slideno, (0..10) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slides/edit.html.erb
<h1>Editing slide</h1>

<%= render 'form' %>

<%= link_to 'Show', @slide %> |
<%= link_to 'Back', slides_path %>

app/views/slides/index.html.erb
<h1>Listing slides</h1>

<table>

<% @slides.each do |slide| %>
	<tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

    <td>
      <%= image_tag(slide.image_url, class: 'list_image') %>
    </td>

    <td class="list_description">
      <dl>
        <dt><%= slide.title %></dt>
        <dd><%= truncate(strip_tags(slide.description),
               length: 80) %></dd>
      </dl>
    </td>
    
    <td class="list_slideno">
    	<p>Slide No.</p>
    	<p> <%= slide.slideno%> </p>
    </td>
    
	  <td class="list_actions"> 
	    <%= link_to 'Show', slide %><br />
	    <%= link_to 'Edit', edit_slide_path(slide) %><br />
	    <%= link_to 'Destroy', slide, method: :delete, data: { confirm: 'Are you sure?' } %><br />
	  </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Slide', new_slide_path %>

app/views/slides/new.html.erb
<h1>New slide</h1>

<%= render 'form' %>

<%= link_to 'Back', slides_path %>

app/views/slides/pro2slider.html.erb
<%= form_for(@slide) do |f| %>
  <% if @slide.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@slide.errors.count, "error") %> prohibited this slide from being saved:</h2>

      <ul>
      <% @slide.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title, :value => @product.title %>
  </div>
  
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url, :value => @product.image_url %>
  </div>
  
  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url, :value => product_path(@product) %>
  </div>
  
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description, :value => @product.description %>
  </div>
  
  <div class="field">
    <%= f.label "Slide No." %><br />
    <%= f.select :slideno, (0..10) %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/slides/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_slide_path(@slide) %> |
<%= link_to 'Back', slides_path %>