config/routes.rb
Depot::Application.routes.draw do

  resources :slides

  resources :categories

  get "contacts/index"

  get "contacts/update"

  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  match "/slides/pro2slider/:id" => "slides#pro2slider"
  
  get 'register' => 'users#new'
  scope '(:locale)' do
    resources :contacts
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, on: :member
      put :decrement, on: :member
      put :increase, on: :member
    end
    root to: 'store#index', as: 'store'
  end
end

app/models/product.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
class Product < ActiveRecord::Base
  CATEGORIES = []
  Category.all.each do |category|
    CATEGORIES << category.name
  end
  
  has_many :line_items
  has_many :orders, through: :line_items
  has_and_belongs_to_many :categories
  #...

  before_destroy :ensure_not_referenced_by_any_line_item

  attr_accessible :description, :image_url, :price, :title, :features, :image_url2, :image_url3, :image_url4, :image_url5, :image_url6,:category_ids
  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
# 
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
    with:    %r{\.(gif|jpg|png)\Z}i,
    message: 'must be a URL for GIF, JPG or PNG image.'
  }
  validates :title, length: {minimum: 10}

  private

    # ensure that there are no line items referencing this product
    def ensure_not_referenced_by_any_line_item
      if line_items.empty?
        return true
      else
        errors.add(:base, 'Line Items present')
        return false
      end
    end
    
end

app/controllers/products_controller.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
class ProductsController < ApplicationController
  skip_before_filter :authorize
  skip_before_filter :require_admin, only: [:show,:index,:decrement,:increase]
  # GET /products
  # GET /products.json
  def index
    @products = Product.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @products }
    end
  end

  # GET /products/1
  # GET /products/1.json
  def show
    @product = Product.find(params[:id])
    unless (session[:product] and session[:product][@product.id]) 
        session[:product] = { @product.id => {:id => @product.id, :quantity => 1}}
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/new
  # GET /products/new.json
  def new
    @product = Product.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @product }
    end
  end

  # GET /products/1/edit
  def edit
    @product = Product.find(params[:id])
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(params[:product])

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product,
          notice: 'Product was successfully created.' }
        format.json { render json: @product, status: :created,
          location: @product }
      else
        format.html { render action: "new" }
        format.json { render json: @product.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # PUT /products/1
  # PUT /products/1.json
  def update
    params[:product][:category_ids] ||= []
    @product = Product.find(params[:id])

    respond_to do |format|
      if @product.update_attributes(params[:product])
        format.html { redirect_to @product,
          notice: 'Product was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @product.errors,
          status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product = Product.find(params[:id])
    @product.destroy

    respond_to do |format|
      format.html { redirect_to products_url }
      format.json { head :no_content }
    end
  end

  def who_bought
    @product = Product.find(params[:id])
    respond_to do |format|
      format.html
      format.xml
      format.atom
      format.json { render json: @product.to_json(include: :orders) }
    end
  end
  
  def decrement
    @product = Product.find_by_id(params[:id])
    if session[:product][@product.id][:quantity] >=2
      session[:product][@product.id][:quantity] -= 1
    end

    respond_to do |format|
      format.html { redirect_to @product }
      format.js
      format.json { head :no_content }
    end
  end
  
  def increase
    @product = Product.find_by_id(params[:id])
    session[:product][@product.id][:quantity] += 1

    respond_to do |format|
      format.html { redirect_to @product, notice: "Product was successfully updated.#{session[:product][@product.id][:quantity]}"}
      format.js
      format.json { head :no_content }
    end
  end
      
end

app/helpers/products_helper.rb
#---
# Excerpted from "Agile Web Development with Rails",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/rails4 for more book information.
#---
module ProductsHelper
  def category_check(cate)
    if @product
       @product.categories.include?(cate)
    else
      false
    end
  end
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %>
      prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :features %><br />
<!-- START_HIGHLIGHT -->
    <%= f.text_area :features, rows: 6 %>
<!-- END_HIGHLIGHT -->
  </div>
  <div class="field">
    <%= f.label :description %><br />
<!-- START_HIGHLIGHT -->
    <%= f.text_area :description, rows: 6 %>
<!-- END_HIGHLIGHT -->
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :image_url2 %><br />
    <%= f.text_field :image_url2 %>
  </div>
  <div class="field">
    <%= f.label :image_url3 %><br />
    <%= f.text_field :image_url3 %>
  </div>
  <div class="field">
    <%= f.label :image_url4 %><br />
    <%= f.text_field :image_url4 %>
  </div>
  <div class="field">
    <%= f.label :image_url5 %><br />
    <%= f.text_field :image_url5 %>
  </div>
  <div class="field">
    <%= f.label :image_url6 %><br />
    <%= f.text_field :image_url6 %>
  </div>
  <div class="field">
    <%= f.label :price %><br />
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <% for cate in Category.find(:all) %>
       <%= check_box_tag "product[category_ids][]", cate.id, category_check(cate) %> <!-- # category_check is a helper method--> 
       <%= cate.name %>
    <% end -%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/_quantity.html.erb
<div id = "quantityInput">
	<%= form_tag(line_items_path(:id => session[:product][@product.id][:id]),:method => "post") do %> 
		<ul>
			<li>
				<label for="quantity">Number of items</label>
				<%= number_field_tag :quantity, session[:product][@product.id][:quantity],:min => 1, :max => 100%>
			</li>
			<li>
				<%= submit_tag "Add to cart"%>
			</li>
		</ul>
	<% end %>
</div>
				


<!--
<div id= "quantityMinus">
	<%= button_to "-", decrement_product_path(session[:product][@product.id]), :method =>:put, :remote => true%>
</div>

<div id= "quantityPlus">
	<%= button_to "+", increase_product_path(session[:product][@product.id]), :method =>:put, :remote => true, :class => "quantityPlus"%>
</div>

<%= form_tag(line_items_path(:id => session[:product][@product.id][:id]),:method => "post") do %> 
	<div id= "quantityInput">
	  <%= text_field_tag :quantity, session[:product][@product.id][:quantity],:size => 3%>
	</div>	
	<br/>
	<div class="quantityInput">
	  <%= submit_tag "Add to cart"%>
	</div>
<% end %>
//-->

app/views/products/decrement.js.erb
$('#quantity').html("<%=j render "quantity" %>");

app/views/products/edit.html.erb
<h1>Editing product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/increase.js.erb
$('#quantity').html("<%=j render "quantity" %>");

app/views/products/index.html.erb
<h1>Listing products</h1>

<table>
<% @products.each do |product| %>
  <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

    <td>
      <%= image_tag(product.image_url, class: 'list_image') %>
    </td>

    <td class="list_description">
      <dl>
        <dt><%= product.title %></dt>
        <dd><%= truncate(strip_tags(product.description),
               length: 80) %></dd>
      </dl>
    </td>

    <td class="list_actions">
      <%= link_to 'Show', product %><br/>
      <%= link_to 'Edit', edit_product_path(product) %><br/>
      <%= link_to 'Destroy', product, method: :delete,
                  data: { confirm: 'Are you sure?' } %><br/>
      <%= link_to 'Promote in slider', "/slides/pro2slider/#{product.id}" %><br/>
    </td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New product', new_product_path %>

app/views/products/new.html.erb
<h1>New product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<% if notice %>
<p id="notice"><%= notice %></p>
<% end %>
	
<div id="wrapper">																																																																																																				
	<div id="content_inside">
		<div id="main_block" class="style1">																																																																													
			<div id="item">
				<h4><%= @product.title%></h4><br />
				<div class="big_view">
					<%=image_tag(@product.image_url, :alt => "", :width=>"311", :height=>"319")%><br />
					<span><%= @product.price %></span>
				</div>
				<div class="scroll">
					<a href="#"><img src="images/pic1.jpg" alt="" width="62" height="62" /></a>
					<a href="#"><img src="images/pic2.jpg" alt="" width="62" height="62" /></a>
					<a href="#"><img src="images/pic3.jpg" alt="" width="62" height="62" /></a>
					<a href="#"><img src="images/pic4.jpg" alt="" width="62" height="62" /></a>
					<a href="#"><img src="images/pic5.jpg" alt="" width="62" height="62" /></a>
					<a href="#"><img src="images/pic6.jpg" alt="" width="62" height="62" /></a>
				</div>
			</div>
			<div class="description">
				<p>
					<strong><%= @product.features%></strong><br /> 
					<%= sanitize(@product.description) %> 
				</p>
				<div id= "quantity">
					<p>
						<%= render 'quantity'%>
					</p>
				</div>
			</div>
		</div>
	</div>
</div>

<p>
  <b>Title:</b>
  <%= @product.title %>
</p>

<p>
  <b>Description:</b>
  <%= @product.description %>
</p>

<p>
  <b>Image url:</b>
  <%= @product.image_url %>
</p>

<p>
  <b>Price:</b>
  <%= @product.price %>
</p>

<% if session[:user_id] and User.find_by_id(session[:user_id]).user_type == "admin"%>
	<%= link_to 'Edit', edit_product_path(@product) %> |
	<%= link_to 'Back', products_path %>
<% end %>

app/views/products/who_bought.html.erb
<h3>People Who Bought <%= @product.title %></h3>

<ul>
  <% for order in @product.orders %>
    <li>
      <%= mail_to order.email, order.name %>
    </li>
  <% end %>
</ul>