config/routes.rb
Depot::Application.routes.draw do

  resources :slides

  resources :categories

  get "contacts/index"

  get "contacts/update"

  get 'admin' => 'admin#index'
  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end
  
  match "/slides/pro2slider/:id" => "slides#pro2slider"
  
  get 'register' => 'users#new'
  scope '(:locale)' do
    resources :contacts
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, on: :member
      put :decrement, on: :member
      put :increase, on: :member
    end
    root to: 'store#index', as: 'store'
  end
end

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
  <title>7 Days 11 Hours Online Store</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  
  <script>
  	$(window).load(function() {    
			//whole page display background
			var theWindow        = $(window),
			    $bg              = $("#bg"),
			    aspectRatio      = $bg.width() / $bg.height();
			function resizeBg() {
				if ( (theWindow.width() / theWindow.height()) < aspectRatio ) {
				    $bg
				    	.removeClass()
				    	.addClass('bgheight');
				} else {
				    $bg
				    	.removeClass()
				    	.addClass('bgwidth');
				}
			}
			theWindow.resize(resizeBg).trigger("resize");
			
			// Photo gallery > Vertical
			$(".photosgallery-vertical").sliderkit({
				circular:true,
				mousewheel:true,
				shownavitems:4,
				verticalnav:true,
				navclipcenter:true,
				auto:true,
				autostill:true,
				panelfxspeed:400,
				timer:true
			});

		});
  </script>
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
	<%= image_tag("1.jpg", :id=>"bg", :alt=>"") %>
	<div id="header">																																																																								
		<div id="header_inside">
			<%= image_tag("header.jpg",:alt=>"header", :width=>"999", :height=>"222", :border=>"0", :usemap=>"#Map") %> <br />																																										
			<ul id="menu">
				<li><%= link_to t('.home'), store_url, :class=>"but1"%></li>
				<li><a href="index2.html" class="but2">About Us</a></li>
				<li><a href="index2.html" class="but3">News &amp; Events</a></li>
				<li><a href="index2.html" class="but4">Services</a></li>
				<li><a href="localhost:3000/login" class="but5">My Account</a></li>
				<li><%= link_to t('.contact'), contacts_path, :class=>"but6"%></li>
			</ul>
			
			<map name="Map">
       <area shape="rect" coords="78,45,312,119" href= "http://localhost:3000/">
       <area shape="poly" coords="670,87,719,78,727,123,677,130" href= "http://localhost:3000/">
       <area shape="poly" coords="776,124,818,152,793,189,751,160" href="http://localhost:3000/login">
       <area shape="poly" coords="834,52,885,61,878,105,828,96" href="#">
			</map>
		</div>
	</div>
	
  <div id="wrapper">
  	<div id="content_inside">
			<div id="sidebar">
				<!-- START:hidden_div -->
		      <% if @cart %>
		        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
		          <%= render @cart %>
		        <% end %>
		      <% end %>
		    <!-- END:hidden_div -->
		    <%= image_tag("title1.gif", :width=>"174", :height=>"30", :alt=>"") %> <br />																																																																		
				<ul id="list">
					<li class="color"><a href="#">Illum secundum</a></li>
					<li><a href="#">Tamen causa ut diam</a></li>
					<li class="color"><a href="#">Appellatio vel hos autem</a></li>
					<li><a href="#">Consequat</a></li>
					<li class="color"><a href="#">Nibh valde tincidunt</a></li>
					<li><a href="#">Illum secundum</a></li>
					<li class="color"><a href="#">Appellatio vel</a></li>
					<li><a href="#">Illum secundum</a></li>
					<!-- START_login -->      
		      <% unless session[:user_id]%>
		      	<br />
		      	<li><%= link_to 'Login', login_url%></li>
		      	<li><%= link_to 'Register', register_url%></li>
		      	<br />
		      <% end %>
					<!-- END_login -->
		      <% if session[:user_id] %>
	          <li><%= link_to 'Orders',   orders_path   %></li>
	          <% if User.find_by_id(session[:user_id]).user_type == "admin"%>
		          <li><%= link_to 'Products', products_path %></li>
		          <li><%= link_to 'Users',    users_path    %></li>
		          <li><%= link_to 'Admin',    admin_path    %></li>
		          <li><%= link_to 'Slider',   slides_path    %></li>
	          <% end %>
		        <li> <%= button_to 'Logout', logout_path, method: :delete   %> </li>
		      <% end %>
		    </ul>
    	</div>
    	
	    <div id="main_block">
	      <%= yield %>
	    </div>
	  </div>
  </div>
</body>
</html>